### ISSUE TITLE
How to listen to "onAction" in mobx-state-tree branch 

### ISSUE THREAD

**Issue by KatSick** [mweststrate/react-mobx-shop#2]
I'm try to add `onAction` from mobx-state-tree (in branch mobx-state-tree) to get complete snapshot of the store to send it via WebSockets.  Here is an example.

```
onAction(shop, () => console.log('some action occurred'))
```

However, when app is starting i receive error message when go throughout navigation:
```
Uncaught Error: Argument 0 that was passed to action 'openBooksPage' should be a primitive, model object or plain object, received a SyntheticMouseEvent
```

How can i avoid this ?

UPDATE 1:

It also occurred when i reload page or `updateBooks()` triggered.

Thanks in advance

<details>
  <summary>Complete error (updateBooks) msg</summary>
Failed to load books  Error: Argument 0 that was passed to action 'updateBooks' should be a primitive, model object or plain object, received a Array
    at serializeArgument (http://localhost:3000/static/js/bundle.js:40167:16)
    at http://localhost:3000/static/js/bundle.js:40213:68
    at Array.map (native)
    at http://localhost:3000/static/js/bundle.js:40213:33
    at runNextMiddleware (http://localhost:3000/static/js/bundle.js:40116:21)
    at runMiddleWares (http://localhost:3000/static/js/bundle.js:40120:13)
    at BookStore.actionInvoker (http://localhost:3000/static/js/bundle.js:40141:25)
    at BookStore.updateBooks (eval at createNamedFunction (http://localhost:3000/static/js/bundle.js:1:1), <anonymous>:3:42)
    at http://localhost:3000/static/js/bundle.js:49546:20
</details>

<details>
  <summary>Complete error (navigation) msg</summary>
Uncaught Error: Argument 0 that was passed to action 'openBooksPage' should be a primitive, model object or plain object, received a SyntheticMouseEvent
    at serializeArgument (http://localhost:3000/static/js/bundle.js:40163:16)
    at http://localhost:3000/static/js/bundle.js:40209:68
    at Array.map (native)
    at http://localhost:3000/static/js/bundle.js:40209:33
    at runNextMiddleware (http://localhost:3000/static/js/bundle.js:40112:21)
    at runMiddleWares (http://localhost:3000/static/js/bundle.js:40116:13)
    at AnonymousModel.actionInvoker (http://localhost:3000/static/js/bundle.js:40137:25)
    at AnonymousModel.openBooksPage (eval at createNamedFunction (http://localhost:3000/static/js/bundle.js:39117:13), <anonymous>:3:44)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:17166:17)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:16949:22)
</details>

<details>
 <summary>Complete index.js</summary>
import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'mobx-react'
import { reaction } from 'mobx'

import createRouter from './utils/router'
import App from './components/App'
import './index.css'

import { getSnapshot, onAction } from 'mobx-state-tree';

import { ShopStore } from './stores/ShopStore'

const fetcher = url => window.fetch(url).then(response => response.json())
const shop = ShopStore.create({}, {
  fetch: fetcher,
  alert: m => window.alert(m)
})
window.shop = shop // for playing around

ReactDOM.render(
  <Provider shop={shop}>
    <App />
  </Provider>,
  document.getElementById('root')
)

onAction(shop, () => console.log('some action occurred'))

reaction(
  () => shop.view.currentUrl,
  (path) => {
    if (window.location.pathname !== path)
      window.history.pushState(null, null, path)
  }
)

const router = createRouter({
  "/book/:bookId": ({bookId}) => shop.view.openBookPageById(bookId),
  "/cart":         shop.view.openCartPage,
  "/":             shop.view.openBooksPage
})

window.onpopstate = function historyChange(ev) {
  if (ev.type === "popstate")
    router(window.location.pathname)
}

router(window.location.pathname)
</details>

**Comment by KatSick** [comment]
I resolved this issue with changes to `updateBooks` and `openCardPage` and `openBooksPage` methods.

Now `updateBooks` looks `updateBooks({ json })` instead of `updateBooks(json)` (as far as i understand mobx-state-tree requires and object as arguments.

And `openCardPage` and `openBooksPage` now executed without event passed
